# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0003_auto_20161210_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
