# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0007_location_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.FloatField(default=1.5),
            preserve_default=False,
        ),
    ]
