# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0008_auto_20161225_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='status',
        ),
    ]
